# Generated by Django 3.2.4 on 2021-06-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idproducto', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Modelo', models.CharField(max_length=50)),
                ('Stock', models.IntegerField(default='0')),
                ('Precio', models.IntegerField()),
                ('Marca', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=2000)),
            ],
        ),
    ]
