# Generated by Django 3.2.4 on 2021-06-22 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idusuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('f_nacto', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Modelo',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Precio',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Stock',
            new_name='stock',
        ),
        migrations.CreateModel(
            name='seguimiento',
            fields=[
                ('idseguimiento', models.IntegerField(primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=50)),
                ('estado_envio', models.CharField(max_length=10)),
                ('idproducto', models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='idproducto_sk', to='app_software.producto')),
                ('idusuario', models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='idusuario_sk', to='app_software.usuario')),
                ('stock', models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='stock_sk', to='app_software.producto')),
            ],
        ),
    ]
